/* ============================================================
   HIGHLIGHTER — Regex-based SPL syntax colorizer
   ============================================================ */

const KEYWORDS = [
  'index', 'sourcetype', 'earliest', 'latest', 'stats', 'table', 'sort',
  'eval', 'where', 'search', 'by', 'as', 'rex', 'rename', 'fields',
  'dedup', 'head', 'tail', 'top', 'rare', 'timechart', 'chart',
  'transaction', 'lookup', 'inputlookup', 'outputlookup', 'append',
  'join', 'union', 'fillnull', 'replace', 'rex', 'streamstats',
  'eventstats', 'sistats', 'tstats', 'mstats', 'pivot',
  'IN', 'OR', 'AND', 'NOT'
];

// Escape keyword for use in regex alternation
function escRx(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

// Build one big ordered alternation — order matters (most specific first)
const TOKEN_RULES = [
  // Comments (#...)
  { cls: 'spl-comment',  rx: /#[^\n]*/g },
  // Pipe
  { cls: 'spl-pipe',     rx: /\|/g },
  // Quoted strings
  { cls: 'spl-value',    rx: /"[^"]*"/g },
  // IP addresses / CIDR
  { cls: 'spl-value',    rx: /\b\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}(?:\/\d{1,2})?\b/g },
  // Time values like -1h -15m -7d
  { cls: 'spl-value',    rx: /-\d+[smhdwqyMY]\b/g },
  // Operators == != >= <= > <
  { cls: 'spl-operator', rx: /[!=<>]+/g },
  // field=value or field!=value — capture field name
  { cls: 'spl-field',    rx: /\b([a-zA-Z_][a-zA-Z0-9_.]*)(?=[!=<>])/g },
  // Numbers
  { cls: 'spl-value',    rx: /\b\d+(?:\.\d+)?\b/g },
  // Keywords (word boundary)
  { cls: 'spl-keyword',  rx: new RegExp(`\\b(${KEYWORDS.map(escRx).join('|')})\\b`, 'g') }
];

/**
 * Tokenize raw SPL and return an HTML string with syntax spans.
 * The input is generated by query-engine.js — it's not user innerHTML.
 * @param {string} raw
 * @returns {string}
 */
export function highlight(raw) {
  if (!raw) return '';

  // We'll do a single-pass positional tokenizer to avoid overlapping matches.
  // Build an array of {start, end, cls} segments, sort, then render.

  const text = raw;
  const segments = []; // { start, end, cls }
  const covered = new Uint8Array(text.length); // bitmask: 1 = already claimed

  for (const rule of TOKEN_RULES) {
    rule.rx.lastIndex = 0;
    let m;
    while ((m = rule.rx.exec(text)) !== null) {
      const start = m.index;
      const end   = m.index + m[0].length;
      // Skip if any byte in this range is already claimed
      let clash = false;
      for (let i = start; i < end; i++) {
        if (covered[i]) { clash = true; break; }
      }
      if (!clash) {
        segments.push({ start, end, cls: rule.cls });
        for (let i = start; i < end; i++) covered[i] = 1;
      }
    }
  }

  // Sort segments by start position
  segments.sort((a, b) => a.start - b.start);

  // Build output
  let out = '';
  let pos = 0;
  for (const seg of segments) {
    if (seg.start > pos) {
      out += escapeHtml(text.slice(pos, seg.start));
    }
    out += `<span class="${seg.cls}">${escapeHtml(text.slice(seg.start, seg.end))}</span>`;
    pos = seg.end;
  }
  if (pos < text.length) {
    out += escapeHtml(text.slice(pos));
  }

  return out;
}

function escapeHtml(s) {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
